### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by strqw** [NickTheHuy/CockPY#10]
127.0.0.1:51581: client connect
127.0.0.1:51581: error establishing server connection: [WinError 1225] The remote computer refused the network connection
127.0.0.1:51581: GET http://127.0.0.1:8099/query_region_list?version=OVSWIN0.7.1&lang=1&platform=3&binary=1&time=948
 << [WinError 1225] The remote computer refused the network connection
127.0.0.1:51581: client disconnect
![image](https://github.com/Hiro420/CockPY/assets/104841307/0e45fa8a-f125-495b-8dc0-b8962907c08c)
![image](https://github.com/Hiro420/CockPY/assets/104841307/3c1dae01-f5c7-4e01-a939-dcb0f73d6477)

**Comment by Minhhok** [comment]
I know it is really late to reply or you already solved your problem. For someone have same problem you need to start proxy.py by cmd type "py proxy.py"

**Comment by Hiro420** [comment]
> I know it is really late to reply or maybe you already solved your problem. For someone have same problem you need to start proxy.py by cmd type "py proxy.py" to find some missing modules

not "py proxy.py" but "mitmdump -s proxy.py -k"
