### ISSUE TITLE
cannot connect server

### ISSUE THREAD

**Issue by dabao1955** [NickTheHuy/CockPY#8]
127.0.0.1 - - [19/Apr/2023 10:43:18] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:43:18] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:43:19] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:43:19] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:43:19] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:43:22] "GET http://dispatch.osglobal.yuanshen.com:12401/query_region_list?version=OVSAndriod0.7.1&lang=2&platform=2&binary=1&time=115 HTTP/1.1" 404 943
127.0.0.1 - - [19/Apr/2023 10:43:35] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:43:35] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:43:36] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:43:36] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:43:36] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:43:36] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:43:36] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:43:36] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:43:37] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:43:37] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:43:38] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:43:38] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:43:39] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:43:39] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:43:39] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:43:41] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:43:41] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:43:42] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:43:42] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:43:42] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:43:46] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:43:47] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:43:47] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:43:47] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:43:47] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:43:55] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:43:56] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:43:56] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:43:56] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:43:56] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:44:12] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:44:13] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:44:13] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:44:13] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
127.0.0.1 - - [19/Apr/2023 10:44:14] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:44:46] "GET http://www.googleapis.cn/generate_204 HTTP/1.1" 404 798
127.0.0.1 - - [19/Apr/2023 10:44:46] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
127.0.0.1 - - [19/Apr/2023 10:44:46] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
127.0.0.1 - - [19/Apr/2023 10:44:47] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
127.0.0.1 - - [19/Apr/2023 10:44:47] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
192.168.0.101 - - [19/Apr/2023 10:45:51] "CONNECT conn-service-cn-05.allawntech.com:443 HTTP/1.1" 404 818
192.168.0.101 - - [19/Apr/2023 10:45:51] "GET http://conn-service-cn-04.allawntech.com/generate204 HTTP/1.1" 404 844
192.168.0.101 - - [19/Apr/2023 10:45:52] "GET http://www.google.cn/generate_204 HTTP/1.1" 404 786
192.168.0.101 - - [19/Apr/2023 10:45:52] "CONNECT www.google.cn:443 HTTP/1.1" 404 758
![Screenshot_2023-04-19-10-44-52-29_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/79307765/232953951-c3df02fb-d2b3-4f6e-a28d-b16c8d40f20b.jpg)

**Comment by NickTheHuy** [comment]
Use it for PC, not android

**Comment by NickTheHuy** [comment]
because its not built for android version?

**Comment by dabao1955** [comment]
> 

Do you mean server-side? Or Genshin apk file?
